import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getSectionByKey } from './baspiSchema';

interface SectionData {
  sectionKey: string;
  title: string;
  data: Record<string, unknown>;
}

export function generatePIF(
  propertyAddress: string,
  sellerName: string,
  sections: SectionData[]
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title page
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Property Information Form', pageWidth / 2, 40, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Based on BASPI (Buying & Selling Property Information)', pageWidth / 2, 52, { align: 'center' });

  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.5);
  doc.line(20, 60, pageWidth - 20, 60);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Property:', 20, 75);
  doc.setFont('helvetica', 'normal');
  doc.text(propertyAddress || 'Not specified', 60, 75);

  doc.setFont('helvetica', 'bold');
  doc.text('Seller:', 20, 85);
  doc.setFont('helvetica', 'normal');
  doc.text(sellerName || 'Not specified', 60, 85);

  doc.setFont('helvetica', 'bold');
  doc.text('Date:', 20, 95);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleDateString('en-GB'), 60, 95);

  let currentY = 115;

  // Part A header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Part A - Material Facts', 20, currentY);
  currentY += 10;

  // Render each section
  for (const section of sections) {
    const sectionDef = getSectionByKey(section.sectionKey);
    if (!sectionDef) continue;

    // Check if we need a new page for Part B header
    if (sectionDef.part === 'B' && sectionDef.key === 'legal_ownership') {
      doc.addPage();
      currentY = 20;
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('Part B - Legal & Conveyancing Information', 20, currentY);
      currentY += 10;
    }

    // Check page space
    if (currentY > 250) {
      doc.addPage();
      currentY = 20;
    }

    // Section title
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(59, 130, 246);
    doc.text(section.title, 20, currentY);
    doc.setTextColor(0, 0, 0);
    currentY += 4;

    // Build rows from field data
    const rows: string[][] = [];

    if (sectionDef.fields) {
      for (const field of sectionDef.fields) {
        const value = section.data[field.key];
        if (value === undefined || value === null || value === '') continue;

        // Check showWhen condition
        if (field.showWhen) {
          const parentVal = section.data[field.showWhen.field];
          if (parentVal !== field.showWhen.value) continue;
        }

        let displayValue: string;
        if (typeof value === 'boolean') {
          displayValue = value ? 'Yes' : 'No';
        } else if (field.options) {
          const opt = field.options.find(o => o.value === value);
          displayValue = opt ? opt.label : String(value);
        } else {
          displayValue = String(value);
        }

        rows.push([field.label, displayValue]);
      }
    }

    if (rows.length > 0) {
      autoTable(doc, {
        startY: currentY,
        head: [['Question', 'Answer']],
        body: rows,
        theme: 'striped',
        headStyles: {
          fillColor: [59, 130, 246],
          textColor: 255,
          fontStyle: 'bold',
        },
        styles: {
          fontSize: 9,
          cellPadding: 3,
        },
        columnStyles: {
          0: { cellWidth: 80, fontStyle: 'bold' },
          1: { cellWidth: 'auto' },
        },
        margin: { left: 20, right: 20 },
      });

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      currentY = (doc as any).lastAutoTable.finalY + 10;
    } else {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.text('No data provided for this section.', 25, currentY + 4);
      currentY += 12;
    }
  }

  // Footer on each page
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pageCount = (doc as any).getNumberOfPages?.() ?? (doc.internal as any).getNumberOfPages?.() ?? 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by PIF Generator`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc;
}
