import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { BASPI_SECTIONS } from './baspiSchema';

interface SectionData {
  sectionKey: string;
  data: Record<string, unknown>;
}

export function generatePifPdf(
  sections: SectionData[],
  propertyAddress: string,
  sellerName: string
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Property Information Form', pageWidth / 2, 28, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('BASPI Compliant — All Seller Responses', pageWidth / 2, 36, { align: 'center' });

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, 41, pageWidth - 20, 41);

  // Property info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  let y = 50;

  doc.setFont('helvetica', 'bold');
  doc.text('Property:', 20, y);
  doc.setFont('helvetica', 'normal');
  doc.text(propertyAddress || 'Not specified', 55, y);

  y += 7;
  doc.setFont('helvetica', 'bold');
  doc.text('Seller:', 20, y);
  doc.setFont('helvetica', 'normal');
  doc.text(sellerName || 'Not specified', 55, y);

  y += 7;
  doc.setFont('helvetica', 'bold');
  doc.text('Date:', 20, y);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  }), 55, y);

  y += 14;

  // Build section data map
  const dataMap: Record<string, Record<string, unknown>> = {};
  for (const s of sections) {
    dataMap[s.sectionKey] = s.data || {};
  }

  // Render each section
  for (const sectionDef of BASPI_SECTIONS) {
    const data = dataMap[sectionDef.key] || {};

    // Check if we need a new page
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    // Section header
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175); // blue-800
    doc.text(sectionDef.title, 20, y);
    y += 2;

    // Build rows for visible fields
    const rows: [string, string][] = [];
    for (const field of sectionDef.fields) {
      // Skip conditional fields whose condition isn't met
      if (field.showWhen && data[field.showWhen.field] !== field.showWhen.value) {
        continue;
      }

      const rawValue = data[field.key];
      const displayValue = formatValue(rawValue, field.type, field.options);
      rows.push([field.label, displayValue]);
    }

    if (rows.length === 0) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(130, 130, 130);
      doc.text('No answers provided', 20, y + 6);
      y += 14;
      continue;
    }

    autoTable(doc, {
      startY: y,
      head: [['Question', 'Answer']],
      body: rows,
      theme: 'striped',
      headStyles: {
        fillColor: [30, 64, 175],
        textColor: 255,
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 9,
        cellPadding: 3,
      },
      columnStyles: {
        0: { cellWidth: 75, fontStyle: 'bold', textColor: [50, 50, 50] },
        1: { cellWidth: 'auto' },
      },
      margin: { left: 20, right: 20 },
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // Footer on each page
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pageCount = (doc as any).getNumberOfPages?.() ?? (doc.internal as any).getNumberOfPages?.() ?? 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | Property Information Form | Generated by PIF Generator`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    );
  }

  return doc;
}

function formatValue(
  value: unknown,
  type: string,
  options?: { value: string; label: string }[]
): string {
  if (value === undefined || value === null || value === '') return '—';

  if (type === 'boolean') {
    return value === true ? 'Yes' : value === false ? 'No' : String(value);
  }

  if (type === 'select' && options) {
    const opt = options.find(o => o.value === value);
    if (opt) return opt.label;
  }

  if (type === 'date' && typeof value === 'string') {
    try {
      return new Date(value).toLocaleDateString('en-GB', {
        day: 'numeric', month: 'long', year: 'numeric',
      });
    } catch {
      return String(value);
    }
  }

  return String(value);
}
